# Generated by Django 3.0.3 on 2020-04-03 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('animal_id', models.AutoField(primary_key=True, serialize=False)),
                ('animal_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('breed_id', models.AutoField(primary_key=True, serialize=False)),
                ('breed_name', models.CharField(max_length=50)),
                ('lifespan', models.IntegerField()),
                ('gestation_period', models.IntegerField()),
                ('average_height', models.FloatField()),
                ('daily_sleep', models.IntegerField()),
                ('diet_chart', models.CharField(max_length=1000)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.Animal')),
            ],
        ),
    ]
