# Generated by Django 3.0.3 on 2020-04-03 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Address',
        ),
    ]
