# Generated by Django 3.0.3 on 2020-07-24 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='doctor_reg_no',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
