# Generated by Django 3.0.3 on 2020-07-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='pet_breed',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='seller',
            name='pet_gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=10),
        ),
        migrations.AlterField(
            model_name='seller',
            name='pet_name',
            field=models.CharField(max_length=120),
        ),
    ]
