# Generated by Django 3.0.3 on 2020-07-24 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_auto_20200722_1814'),
        ('seller', '0002_auto_20200411_1502'),
    ]

    operations = [
    ]
