# Generated by Django 2.2.6 on 2020-07-24 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_auto_20200411_1502'),
        ('seller', '0002_auto_20200722_1814'),
    ]

    operations = [
    ]
