# Generated by Django 3.0.3 on 2020-07-24 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_seller_is_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='doctor_name',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='doctor_reg_no',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seller',
            name='pet_type',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
